site_name: Rucio interaction with the Data Lake and DLaaS for Open Science
site_url: https://rucio-escape-datalake.com/
nav:
    - Authentication: index.md
    - Interacting with Rucio CLI: rucio_cli.md
    - DataLake-as-a-Service for Open Science: dlaas.md
    
theme: readthedocs
