site_name: Rucio interaction with ESCAPE Data Lake 
site_url: https://rucio-escape-datalake.com/
nav:
    - Authentication: auth.md
    - Rucio CLI environment install: cli.md
    - Rucio RESTful APIs: api.md

theme: readthedocs
